name: Zemblanity in Data Science

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-111691674-1'

theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title

port : 4000
url: http://localhost:4000

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]

